---
kind: pipeline
name: molecule-debian-10

platform:
  os: linux
  arch: amd64

steps:
- name: Lint
  image: veselahouba/molecule
  commands:
  - shellcheck_wrapper
  - flake8
  - yamllint .
  - ansible-lint

- name: Molecule test
  image: veselahouba/molecule
  commands:
  - ansible --version
  - molecule --version
  - REF=$$(echo $DRONE_COMMIT_REF | awk -F'/' '{print $$3}'|sed 's/_/-/g')
  - REPO_NAME=$$(echo $DRONE_REPO_NAME | sed 's/_/-/g')
  - MOLECULE_IMAGE=debian-10
  - export MOLECULE_IMAGE REPO_NAME REF
  - molecule test --all
  environment:
    HCLOUD_TOKEN:
      from_secret: HCLOUD_TOKEN
 
